ping:
  route: ping
  args: timestamp
  filter_type: start_with
  filter_word: ping
stats:
  route: stats
  args: content
  filter_type: start_with
  filter_word: stats
rank:
  route: rank
  args: content
  filter_type: start_with
  filter_word: rank
